### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by 3rd-Eden** [bigpipe/bigpipe#60]
```
Please note that this roadmap is work in progress. 
Do not assume that this is final until this message 
has been removed by the topic creator.
```
## 0.8
- [x] Conditional Pagelets #56
## 0.9
- [x] Prepend `_` to each private function in pagelet to prevent collisions with extended functions
- [ ] Realtime dashboard example app (demonstration purposes only) 
- [ ] Rewrite of the internal compiler
- [x] Merge `Page` with `Pagelet` to create a uniform interface #55
## 0.10
- [ ] Realtime dashboard example app (documentation en tutorial around it)
- [ ] TodoMVC sample application
- [ ] Enable sandboxing for client code.
- [ ] Refactor of client code loading and removing the dependence of knowing the pagelet names. 
## 0.11
- [ ] Quicklining/pjax #7 
- [ ] more documentation
- [ ] more tests
